name: Open Pull Request on Tag Push

on:
  push:
    tags:
      - 'v*'

jobs:
  open_pull_request:
    name: 'Open Pull Request'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Get version'
        id: version
        uses: battila7/get-version-action@v2

      - name: 'Extract branch name'
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
              
      - name: 'Open Pull Request'
        id: pull_request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref }}
          title: ${{ steps.version.outputs.version }}
          labels: ${{ steps.version.outputs.version-without-v }}