name: Release

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version'
        required: true
        default: '1.0.0'

env:
  PROJECT_NAME: 'nil70n.AspNet.Helpers.FromClaim'
  PROJECT_PATH: 'src/nil70n.AspNet.Helpers.FromClaim/nil70n.AspNet.Helpers.FromClaim.csproj'
  PKG_OUTPUT_DIR: ${{ github.workspace }}/output
  NUGET_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    environment: release
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
 
      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: 'Restore Packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}
      
      - name: 'Build project'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore -c Release

      - name: 'Pack project'
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build -c Release --include-symbols -p:PackageVersion=${{ github.event.inputs.package_version }} --output ${{ env.PKG_OUTPUT_DIR }}

      - name: 'Push package'
        run: dotnet nuget push ${{ env.PKG_OUTPUT_DIR }}/${{ env.PROJECT_NAME }}.${{ github.event.inputs.package_version }}.nupkg -k ${{ secrets.NUGET_KEY }} -s ${{ env.NUGET_URL }}
