name: Release

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version'
        required: true
        default: '1.0.0'
      release_body:
        description: 'Release body'
        required: true
        default: 'Release 1.0.0'

env:
  PROJECT_NAME: 'nil70n.AspNet.Helpers.FromClaim'
  PROJECT_PATH: 'src/nil70n.AspNet.Helpers.FromClaim/nil70n.AspNet.Helpers.FromClaim.csproj'
  PKG_OUTPUT_DIR: ${{ github.workspace }}/output
  NUGET_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    environment: release
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
 
      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: 'Restore Packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}
      
      - name: 'Build project'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore -c Release

      - name: 'Pack project'
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build -c Release --include-symbols -p:PackageVersion=${{ github.event.inputs.package_version }} --output ${{ env.PKG_OUTPUT_DIR }}

      - name: 'Zip assets'
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ${{ env.PKG_OUTPUT_DIR }}/${{ env.PROJECT_NAME }}.zip ${{ env.PKG_OUTPUT_DIR }}

      - name: 'Create Release'
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.package_version }}
          release_name: v${{ steps.version.outputs.version }}
          body: ${{ github.event.inputs.release_body }}
          draft: false
          prerelease: false

      - name: 'Upload Release Asset'
        id: upload-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ env.PKG_OUTPUT_DIR }}/${{ env.PROJECT_NAME }}.zip
          asset_name: ${{ env.PROJECT_NAME }}.${{ github.event.inputs.package_version }}.nupkg
          asset_content_type: application/zip

      - name: 'Push package'
        run: dotnet nuget push ${{ env.PKG_OUTPUT_DIR }}\*.nupkg -k ${{ secrets.NUGET_KEY }} -s ${{ env.NUGET_URL }}
